Changed client to use latest version of API (1.3) to resolve problem with presentation builder...
com.sun.jersey.api.client.UniformInterfaceException: GET http://trial2.assetbank.co.uk/assetbank-trial17/rest/v1.2/assets/30 returned a response status of 404 Not Found

...this will probably break again when / if a new version of the API is added but rewriting the client to traverse the urls properly or rewriting the API/reprs to return placeholder/variable urls for instance resources
isn't something we have time for at the moment.